### ISSUE TITLE
Example for Piping the Response  to a File 

### ISSUE THREAD

**Issue by thiyaga123** [leukhin/co-request#16]
This is not an issue.  
Can you please give me example code to pipe response to writable file. ?

Example: How to write this below code in co-request ?
request('http://google.com/doodle.png').pipe(fs.createWriteStream('doodle.png'));

**Comment by leukhin** [comment]
Hi @thiyaga123, please go to https://github.com/leukhin/co-request and Cmd/Ctrl + F "To pipe request you should use small helper". This will solve your question! :) 
Good luck!

**Comment by thiyaga123** [comment]
Hi 
   Thanks for the reply.. 

Sorry for noob question.
Could you please give me full example code that read from http and write to file.
I tried below code..  Compiler throwing below error.

error 1 : this.req is uindefined
error 2 : and pipe is undefined.

 function pipeRequest( readable, requestThunk )
            {
                return function ( cb )
                {
                    readable.pipe( requestThunk( cb ) );
                }
            }

  var value = yield pipeRequest( this.req, request(   options ));

**Comment by leukhin** [comment]
@thiyaga123 I think you have missed context of execution. Is it any chance to saw entire file?

**Comment by thiyaga123** [comment]
Hi Dennis

I have attached the entire file.

Thank you

**Comment by thiyaga123** [comment]
var Appconfig = require( "./config" );

var fs = require( "fs" );
var co = require( "co" );
var request = require( "co-request" );
var getDBObject = require( "./db" );


function DownloadFKData()
{
    var dbObj = getDBObject( );
    co( 
        
        function*()
        {
            function pipeRequest( readable, requestThunk )
            {
                return function ( cb )
                {
                    readable.pipe( requestThunk( cb ) );
                }
            }
            
            
            var FKresponse = yield request( Appconfig.Fk_ProductFeedAPI_Level1 );
            
            var FKResponsejson = JSON.parse( FKresponse.body );
            var ListofCategories = FKResponsejson.rawListings;
            
            for ( var categoryname in ListofCategories )
            {
                var category = ListofCategories [categoryname];
                //console.log( category.Variant.get );
                
                //Start Downloading Zip Files
                
                var options = 
 {
                    url: category.Variants.get,
                    headers: {
                        'Fk-Affiliate-Token': Appconfig.Fk_Affiliate_Token,
                        'Fk-Affiliate-Id' : Appconfig.Fk_Affiliate_Id
                    }
                }
                console.log( "Downloading :" + category.availableVariants['v0.1.0'].resourceName );
                //var j = yield request( options );
                var value = yield pipeRequest( this.req, request( options ) );//? how to save this response file ? !!!
                
                
                var i;
            }
        }
    )
    .then(
        function ( value )
        { 
        
        },
    function ( err )
        {
            console.log( err.stack );
        }

    );
     
}

DownloadFKData( );

**Comment by leukhin** [comment]
@thiyaga123 in your case you should try something like this:

```js
function pipeRequest(requestThunk, readable) {
  return function (cb) {
    readable.pipe(requestThunk(cb));
  }
}
var availableVariants = fs.createWriteStream('variants.txt'); // For example it is a file
yield pipeRequest(request(options), availableVariants);
```
After that you should see your response in the file variants.txt. 
i'm not sure for 100%, because I didnt tested this. But give it a try. And except of file use your needed destination source to save or process data.

**Comment by thiyaga123** [comment]
Dear Dennis

Thanks again for the reply. I tried your implementation code..

i got below error:;


Debugger listening on port 5858
Downloading :bags_wallets_belts
Error: Cannot pipe. Not readable.
    at WriteStream.Writable.pipe (_stream_writable.js:162:22)
    at F:\Personal\Amazier.com\SmartShop\SrvSmartShop\import_fk.js:21:30
    at
F:\Personal\Amazier.com\SmartShop\SrvSmartShop\node_modules\co\index.js:1
35:8
    at thunkToPromise
(F:\Personal\Amazier.com\SmartShop\SrvSmartShop\node_modul
es\co\index.js:134:10)
    at toPromise
(F:\Personal\Amazier.com\SmartShop\SrvSmartShop\node_modules\co
\index.js:118:55)
    at next
(F:\Personal\Amazier.com\SmartShop\SrvSmartShop\node_modules\co\inde
x.js:98:29)
    at onFulfilled
(F:\Personal\Amazier.com\SmartShop\SrvSmartShop\node_modules\
co\index.js:68:7)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
